export declare const UI_COPY: Readonly<{
  loading: string;
  preparing: string;
  channels: string;
  settings: string;
  quality: string;
  actions: string;
  reloadStream: string;
  refreshChannels: string;
  noChannel: string;
  buffering: string;
  streamOpening: string;
  recovering: string;
  streamFailed: string;
  cancel: string;
  confirm: string;
  close: string;
  xtreamEntry: Readonly<{
    title: string;
    serverUrl: string;
    username: string;
    password: string;
    connect: string;
    back: string;
    connecting: string;
    required: string;
    auth: string;
    network: string;
    timeout: string;
    notFound: string;
    server: string;
    malformed: string;
    unavailable: string;
  }>;
}>;
