export const UI_COPY = Object.freeze({
  loading: 'Yükleniyor…',
  preparing: 'Hazırlanıyor…',
  channels: 'Kanallar',
  settings: 'Ayarlar',
  quality: 'Kalite',
  actions: 'İşlemler',
  reloadStream: 'Yayını yeniden yükle',
  refreshChannels: 'Kanalları yenile',
  noChannel: 'Kanal seçilmedi',
  buffering: 'Arabelleğe alınıyor',
  streamOpening: 'Yayın açılıyor…',
  recovering: 'Yayın yeniden deneniyor…',
  streamFailed: 'Yayın açılamadı',
  cancel: 'İptal',
  confirm: 'Onayla',
  close: 'Kapat',
  xtreamEntry: Object.freeze({
    title: 'Xtream Codes ile Bağlan',
    serverUrl: "Sunucu URL'si",
    username: 'Kullanıcı adı',
    password: 'Şifre',
    connect: 'Bağlan',
    back: 'Geri',
    connecting: 'Bağlanıyor…',
    required: 'Sunucu, kullanıcı adı ve şifre gerekli.',
    auth: 'Kullanıcı adı veya şifre hatalı.',
    network: 'Sunucuya ulaşılamadı.',
    timeout: 'Bağlantı zaman aşımına uğradı.',
    notFound: 'Sunucu kaynağı bulunamadı.',
    server: 'Sunucu geçici bir hata döndürdü.',
    malformed: 'Sunucu yanıtı desteklenmiyor.',
    unavailable: 'Bağlantı kurulamadı.',
  }),
});
